### ISSUE TITLE
数据侦测数据表数据量信息采集

### ISSUE THREAD

**Issue by ALiXiaolan** [InCar/ta-panel#14]
- 获取数据集中每个数据表的数据量（MB）、数据总条数 
  >请求方式 GET
请求地址：api/mongo/collectionSheetSize
请求参数：无
返回实体：数据表信息对象集合，示例如下：
 [ 
     {
        “collectionName”:"xxx",   --数据表名称
        "collectionCount": 41043741,   --总行数
        "collectionSize": 358899038414   --总数据量大小（MB）
       } 
  ]

**Comment by AceBear** [comment]
issue需要尽量保持一事一议原则，这个issue涉及2个API，需要拆成2个

**Comment by AceBear** [comment]
API需要明确  HTTP method(GET/post/...) , url path(/api/foo/asdf/...) 以及参数返回值的具体名称
总体原则是，实现方看了这个issue，就可以开始写实现的代码了。调用方看了这个issue，也可以知道怎么调用这个api,传哪些参数，返回值是什么样子的
